#!/usr/bin/env python

import sys
import pydraft


commands = {'--serve': pydraft.serve,
            }


def run(args):
    try:
        option = sys.argv[1]
        commands[option]()
    except (IndexError, KeyError) as e:
        print('\n\t'.join(["Usage:",
                           "pydraft --serve",
                           "pydraft --new-key <name> [exp_date]",
                           ]))

if __name__ == "__main__":
    run(sys.argv)
